student_name   = "dmezhva"
student_IDnum  = "3"
zone           = "us-central1-a"
machine_type   = "custom-1-4608"
disk_size 	   = "25"
disk_type 	   = "pd-ssd"
image 		   = "centos-cloud/centos-7"
netpubname	   = "public-subnetwork-vpc"
netprivname	   = "private-subnetwork-vpc"
exfwname       = "external-connect"
infwname	   = "internal-connect"

