project        = "devops-lab-summer"
region         = "us-central1"
zone           = "us-central1-a"
student_name   = "imelnik1"
students_IDnum = "1"
machine_type   = "custom-1-4608"
image_project  = "centos-cloud"
image_family   = "centos-7"
